server:
  port: 8100

spring:
  application:
    name: auto


  datasource:
    url: jdbc:mysql://localhost:3306/autos
    username: root
    password:
    platform: mysql

  jpa:
    hibernate:
      ddl-auto: update

